# generated by datamodel-codegen:
#   filename: runtime-wire-v1.json

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, confloat, conint, constr


class Role(Enum):
    system = 'system'
    user = 'user'
    assistant = 'assistant'
    tool = 'tool'


class InputItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    role: Role
    content: str


class Budget(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    max_tokens: conint(ge=0, le=9007199254740991) | None = None
    maxTokens: conint(ge=0, le=9007199254740991) | None = None
    max_tool_calls: conint(ge=0, le=9007199254740991) | None = None
    maxToolCalls: conint(ge=0, le=9007199254740991) | None = None
    max_retries: conint(ge=0, le=9007199254740991) | None = None
    maxRetries: conint(ge=0, le=9007199254740991) | None = None
    max_duration_ms: conint(ge=0, le=9007199254740991) | None = None
    maxDurationMs: conint(ge=0, le=9007199254740991) | None = None


class Tools(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    name: str


class Parameters(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    type: Literal['object']


class LocalToolSchema(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    name: str
    description: str
    parameters: Parameters


class RuntimeOverrides(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    model: str | None = None
    provider: str | None = None
    sampling_temperature: float | None = None
    budget: Budget | None = None
    tools: list[str | Tools] | None = None
    context: dict[str, Any] | None = None
    local_tool_schemas: list[LocalToolSchema] | None = None


class RunRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_version: str | None = None
    contractVersion: str | None = None
    profile_id: str | None = None
    profileId: str | None = None
    profile_version: str | None = None
    profileVersion: str | None = None
    app_id: str | None = None
    appId: str | None = None
    session_id: str | None = None
    sessionId: str | None = None
    input: str | list[InputItem]
    model: str | None = None
    budget: Budget | None = None
    tools: list[str | Tools] | None = None
    stream: bool | None = None
    idempotency_key: str | None = None
    idempotencyKey: str | None = None
    deadline_ms: conint(ge=0, le=9007199254740991) | None = None
    runtime_overrides: RuntimeOverrides | None = None


class QuestionId(Enum):
    agent_next_readonly_action_v1 = 'agent.next_readonly_action.v1'
    agent_evidence_sufficiency_v1 = 'agent.evidence_sufficiency.v1'


class Questions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['choice']
    instructions: constr(min_length=1, max_length=2048)
    criteria: dict[constr(min_length=1, max_length=128), constr(max_length=512)]
    requiredAbstainOption: Literal[True]


class Constraints(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    maxLatencyMs: conint(ge=1, le=2000)
    shadowOnly: Literal[True]
    noSideEffects: Literal[True]
    maxAttempts: Literal[1]


class DecisionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    requestId: UUID
    runId: constr(min_length=1)
    capability: Literal['semantic.choice.v1']
    questionId: QuestionId
    policyVersion: Literal['shadow.v1']
    dataClassification: Literal['public']
    state: constr(max_length=32768)
    questions: dict[constr(min_length=1, max_length=128), Questions]
    constraints: Constraints


class DeploymentState(Enum):
    candidate_shadow = 'candidate_shadow'
    advisory_shadow = 'advisory_shadow'


class Provider(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Literal['tinymodels']
    version: constr(min_length=1)
    modelId: constr(min_length=1)
    artifactId: str | None = None
    deploymentId: constr(min_length=1)
    deploymentState: DeploymentState


class CalibrationState(Enum):
    uncalibrated = 'uncalibrated'
    calibrated = 'calibrated'
    not_available = 'not_available'


class Results(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['choice']
    value: str
    probabilities: dict[str, confloat(ge=0.0, le=1.0)] | None = None
    rawConfidence: confloat(ge=0.0, le=1.0) | None = None
    calibratedConfidence: confloat(ge=0.0, le=1.0) | None = None
    calibrationState: CalibrationState
    abstained: bool


class Evidence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    inputHash: constr(pattern=r'^sha256-[a-f0-9]{64}$')
    outputHash: constr(pattern=r'^sha256-[a-f0-9]{64}$')
    processUnloaded: bool
    latencyMs: confloat(ge=0.0)


class DecisionResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    requestId: UUID
    provider: Provider
    results: dict[str, Results]
    evidence: Evidence


class Type(Enum):
    run_admitted = 'run.admitted'
    run_started = 'run.started'
    run_created = 'run.created'
    message_delta = 'message.delta'
    message_completed = 'message.completed'
    tool_invoked = 'tool.invoked'
    tool_called = 'tool.called'
    tool_completed = 'tool.completed'
    tool_result = 'tool.result'
    tool_failed = 'tool.failed'
    approval_required = 'approval.required'
    approval_resolved = 'approval.resolved'
    worker_dispatched = 'worker.dispatched'
    worker_completed = 'worker.completed'
    run_completed = 'run.completed'
    run_failed = 'run.failed'
    run_cancelled = 'run.cancelled'


class RunEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    run_id: constr(min_length=1)
    type: Type
    timestamp: AwareDatetime
    data: dict[str, Any]


class Status(Enum):
    admitted = 'admitted'
    running = 'running'
    waiting_for_tool = 'waiting_for_tool'
    waiting_for_worker = 'waiting_for_worker'
    waiting_for_approval = 'waiting_for_approval'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'
    timed_out = 'timed_out'


class Usage(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    prompt_tokens: conint(ge=0, le=9007199254740991) | None
    completion_tokens: conint(ge=0, le=9007199254740991) | None
    total_tokens: conint(ge=0, le=9007199254740991) | None
    tool_calls_count: conint(ge=0, le=9007199254740991)
    retry_count: conint(ge=0, le=9007199254740991)
    duration_ms: conint(ge=0, le=9007199254740991)


class RunResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_version: str | None = None
    run_id: constr(min_length=1)
    id: str | None = None
    status: Status
    profile_id: str | None = None
    profile_version: str | None = None
    messages: list[dict[str, Any]]
    usage: Usage | None = None
    context_receipt: dict[str, Any] | None = None
    evidence_records: list[dict[str, Any]] | None = None
    error: dict[str, Any] | None = None


class ToolResultCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    result: Any
    is_error: bool
    authorization_receipt: dict[str, Any]


class ApprovalResolutionCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approved: bool


class Approval(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    tool_call_id: constr(min_length=1)
    tool_name: constr(min_length=1)
    arguments_hash: constr(min_length=1)
    app_id: constr(min_length=1)
    session_id: constr(min_length=1)
    expires_at: AwareDatetime


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_version: Literal['runtime-wire.v1.0.0']
    run_request: RunRequest
    decision_request: DecisionRequest
    decision_result: DecisionResult
    run_event: RunEvent
    run_result: RunResult
    tool_result_command: ToolResultCommand
    approval_resolution_command: ApprovalResolutionCommand
    approval: Approval
